development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: protlist_dev
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: protlist_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: protlist_production
  pool: 5
  username: rails_user
  password: mint06 